# noinspection PyStatementEffect
{
    'name': 'Advance Material Consumption (With Advance Rights of Requester , Approval and Consumption Manager Access Rights )',
    'version': '16.0.1',
    'category': 'Inventory',
    'summary': 'Material consumption',
    'author': 'TeamUp4Solutions, TaxDotCom',
    'website': 'http://taxdotcom.org/',
    'maintainer': 'Muhammad Umar',
    'depends': ['stock_account', 'account', 'stock', 'uom', 'product'],
    'data': [
        'security/stock_security.xml',
        'security/ir.model.access.csv',
        'views/stock_consumption.xml',
        'views/consumption_lines.xml',
        'views/product.xml',
        'data/ir_sequence.xml',
        'data/stock_location.xml',
        'wizards/adjustment_entry.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 30.00,
    'currency': 'EUR',
    # 'images': ['static/description/banner.png', 'static/description/icon.png'],
    'images': ['static/description/icon.png'],
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
}
